name: CI testing

on: [push,pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        sudo apt install libxerces-c-dev

    - name: Building the project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Building the tests and executing them
      run: |
        cd build
        cd Tests
        make
        ./MolSimTests
